on:
    push:
        branches:
            - DEV

name: Deploy to ...

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                node-version: '12'

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8

            - name: Build
              id: build
              run: |
                  chmod +x ./build.sh
                  ./build.sh

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}


            - name: Docker Build, tag and push
              run: |
                  docker build -t mapstore-dev-aws .
                  docker tag mapstore-dev-aws 703780215332.dkr.ecr.us-east-2.amazonaws.com/mbarto-dev:latest
                  aws ecr get-login-password --region us-east-2 | docker login --password-stdin --username AWS "703780215332.dkr.ecr.us
-east-2.amazonaws.com"
                  docker push 703780215332.dkr.ecr.us-east-2.amazonaws.com/mbarto-dev:latest
