on:
    push:
        branches:
            - DEV

name: Deploy to ...

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                node-version: '12'

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8

            - name: Build
              id: build
              run: |
                  chmod +x ./build.sh
                  ./build.sh
