on:
    push:
        branches:
            - DEV

name: Deploy to ...

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-16.04

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Build
              id: build
              run: |
                  chmod +x ./build.sh
                  ./build.sh
